const translations = {
  es: {
    home: 'Inicio',
    notifications: 'Notificaciones',
    messages: 'Mensajes',
    create: 'Crear',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    profile_edit: 'Editar Perfil',
    change_password: 'Cambiar Contraseña',
    terms_conditions: 'Términos y Condiciones',
    help_support: 'Ayuda y Soporte',
    about: 'Acerca de',
    delete_account: 'Eliminar Cuenta',
    back_to_messages: 'Volver a Mensajes',
    chat_with: 'Chat con',
    type_message: 'Escribe un mensaje...',
    send: 'Enviar',
    no_posts: 'No hay publicaciones todavía. ¡Sé el primero en publicar!',
    no_messages: 'No hay mensajes todavía.',
    no_notifications: 'No hay notificaciones todavía.',
    no_comments: 'No hay comentarios todavía.',
    welcome: 'Bienvenido a MVMood!',
    like: 'Me gusta',
    comment: 'Comentar',
    delete: 'Eliminar',
    comments: 'Comentarios',
    select_language: 'Seleccionar idioma',
    nickname: 'Nickname',
    current_password: 'Contraseña actual',
    new_password: 'Nueva contraseña',
    retype_password: 'Reescribe la nueva contraseña',
    confirm_password: 'Confirmar cambio',
    cancel: 'Cancelar',
    fill_all_fields: 'Completa todos los campos.',
    password_mismatch: 'Las contraseñas no coinciden.',
    password_too_short: 'La nueva contraseña debe tener al menos 6 caracteres.',
    password_updated: 'Contraseña actualizada correctamente.',
    view_profile: 'Ver perfil',
    user_id: 'ID de usuario',
    profile_posts: 'publicaciones',
    block_user: 'Bloquear usuario',
    report_user: 'Reportar usuario',
    user_blocked: 'Usuario bloqueado.',
    user_reported: 'Usuario reportado.',
    user_posts: 'Publicaciones del usuario',
    unknown_user: 'Usuario desconocido',
    no_bio: 'Sin biografía disponible.',
    back: 'Atrás',
    more_options: 'Más opciones',
    profile_more_actions_description: 'Toca el icono de opciones para bloquear o reportar este perfil.',
    report: 'Reportar',
  },
  ca: {
    home: 'Inici',
    notifications: 'Notificacions',
    messages: 'Missatges',
    create: 'Crear',
    settings: 'Configuració',
    logout: 'Tancar Sessió',
    profile_edit: 'Editar Perfil',
    change_password: 'Canviar Contrasenya',
    terms_conditions: 'Termes i Condicions',
    help_support: 'Ajuda i Suport',
    about: 'Sobre Nosaltres',
    delete_account: 'Eliminar Compte',
    back_to_messages: 'Tornar a Missatges',
    chat_with: 'Xat amb',
    type_message: 'Escriu un missatge...',
    send: 'Enviar',
    no_posts: 'No hi ha publicacions encara. Sigues el primer en publicar!',
    no_messages: 'No hi ha missatges encara.',
    no_notifications: 'No hi ha notificacions encara.',
    no_comments: 'No hi ha comentaris encara.',
    welcome: 'Benvingut a MVMood!',
    like: 'M\'agrada',
    comment: 'Comentar',
    delete: 'Eliminar',
    comments: 'Comentaris',
    select_language: 'Selecciona idioma',
    nickname: 'Nickname',
    current_password: 'Contrasenya actual',
    new_password: 'Nova contrasenya',
    retype_password: 'Torna a escriure la nova contrasenya',
    confirm_password: 'Confirmar canvi',
    cancel: 'Cancel·lar',
    fill_all_fields: 'Completa tots els camps.',
    password_mismatch: 'Les contrasenyes no coincideixen.',
    password_too_short: 'La nova contrasenya ha de tenir almenys 6 caràcters.',
    password_updated: 'Contrasenya actualitzada correctament.',
    view_profile: 'Veure perfil',
    user_id: 'ID d\'usuari',
    profile_posts: 'publicacions',
    block_user: 'Bloquejar usuari',
    report_user: 'Reportar usuari',
    user_blocked: 'Usuari bloquejat.',
    user_reported: 'Usuari reportat.',
    user_posts: 'Publicacions de l\'usuari',
    unknown_user: 'Usuari desconegut',
    no_bio: 'Sense biografia disponible.',
    back: 'Enrere',
    more_options: 'Més opcions',
    profile_more_actions_description: 'Toca la icona d\'opcions per bloquejar o reportar aquest perfil.',
    report: 'Reportar',
  },
  en: {
    home: 'Home',
    notifications: 'Notifications',
    messages: 'Messages',
    create: 'Create',
    settings: 'Settings',
    logout: 'Log out',
    profile_edit: 'Profile Edit',
    change_password: 'Change Password',
    terms_conditions: 'Terms and Conditions',
    help_support: 'Help and Support',
    about: 'About',
    delete_account: 'Delete Account',
    back_to_messages: 'Back to Messages',
    chat_with: 'Chat with',
    type_message: 'Type a message...',
    send: 'Send',
    no_posts: 'No posts yet. Be the first to post!',
    no_messages: 'No messages yet.',
    no_notifications: 'No notifications yet.',
    no_comments: 'No comments yet.',
    welcome: 'Welcome to MVMood!',
    like: 'Like',
    comment: 'Comment',
    delete: 'Delete',
    comments: 'Comments',
    select_language: 'Select language',
    nickname: 'Nickname',
    current_password: 'Current password',
    new_password: 'New password',
    retype_password: 'Retype new password',
    confirm_password: 'Confirm change',
    cancel: 'Cancel',
    fill_all_fields: 'Please fill in all fields.',
    password_mismatch: 'Passwords do not match.',
    password_too_short: 'New password must be at least 6 characters.',
    password_updated: 'Password updated successfully.',
    view_profile: 'View Profile',
    user_id: 'User ID',
    profile_posts: 'posts',
    block_user: 'Block User',
    report_user: 'Report User',
    user_blocked: 'User blocked.',
    user_reported: 'User reported.',
    user_posts: 'User posts',
    unknown_user: 'Unknown user',
    no_bio: 'No bio available.',
    back: 'Back',
    more_options: 'More options',
    profile_more_actions_description: 'Tap the options icon to block or report this profile.',
    report: 'Report',
  },
};

export const getTranslation = (lang, key) => {
  return translations[lang][key] || key;
};

export const useLanguage = () => {
  const storedLang = localStorage.getItem('language');
  const lang = storedLang || 'en';
  
  const setLanguage = (newLang) => {
    localStorage.setItem('language', newLang);
    window.location.reload();
  };

  const t = (key) => getTranslation(lang, key);

  return { lang, setLanguage, t };
};
